install.packages("ggplot2")
library(ggplot2)
options(stringsAsFactors=F)
t=read.table("PrincipalComponentAnalysis.matrix",check.names=F,header=T)
table=table(t[,2])
groups=rep(names(table),table)
#data=t[,c(1,3,4,2)]
data=t
attach(t)
pdf("PrincipalComponentAnalysis.pdf")
qplot(x=PC1,y=PC2,data=data,colour=factor(groups))+theme(legend.position="none")+stat_ellipse(lwd=1)
qplot(x=PC2,y=PC3,data=data,colour=factor(groups))+theme(legend.position="none")+stat_ellipse(lwd=1)
qplot(x=PC1,y=PC3,data=data,colour=factor(groups))+theme(legend.position="none")+stat_ellipse(lwd=1)
dev.off()
